workspace:
  base: /go
  path: src/github.com/ColdFreak/goapp

# http://docs.drone.io/cloning/
clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build:
    image: golang
    commands:
      - echo "hi"
      - ls -al
      - kubectl cluster-info
      # - go build

  helm_deploy_staging:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: true
    chart: ./helm/goapp
    release: "goapp"
    wait: true
    recreate_pods: true
    secrets: [api_server, kubernetes_token]
    values_files: ["values.yaml"]
    namespace: drone
    when:
      event: push
      branch: develop
  # ここのnotifyという文字列決まっていないからなんでもいい
  notify:
    image: plugins/slack
    # appsの中からincoming-webhookを選んで、チャンネルを選んでリンクが出てくる
    webhook: https://hooks.slack.com/services/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
    channel: tmp-slack-api-test
    # Slackのデフォルト表記のincoming-webhookからdroneに変更
    username: drone
    template: >
      *{{ build.status }}* <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{ build.commit }}> ({{ build.ref }}) by {{ build.author }}
    when:
      event: [ push, pull_request ]
      status: [ success, failure ]

branches: [develop, feature/*]

services:
  database:
    image: mysql
    # http://docs.drone.io/environment/
    commands:
      - export MYSQL_ROOT_PASSWORD="123"


