workspace:
  base: /go
  path: src/github.com/ColdFreak/goapp

# http://docs.drone.io/cloning/
clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build:
    image: golang
    commands:
      - echo "hi"
      - ls -al

  helm_deploy:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: true
    chart: ./helm/goapp
    release: ${DRONE_BRANCH}
    namespace: drone
    values_files: ["./helm/goapp/values.yaml"]
    debug: true
    prefix: dev
    secrets: [api_server, kubernetes_token]
    values: ingress.hosts=[develop-branch-goapp.so.opensdev.pro]
    # api_server: https://10.32.0.72:6443
    # recreate_pods: true
    # wait: true


  # ここのnotifyという文字列決まっていないからなんでもいい
  notify:
    image: plugins/slack
    # appsの中からincoming-webhookを選んで、チャンネルを選んでリンクが出てくる
    webhook: https://hooks.slack.com/services/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
    channel: tmp-slack-api-test
    # Slackのデフォルト表記のincoming-webhookからdroneに変更
    username: drone
    template: >
      *{{ build.status }}* <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{ build.commit }}> ({{ build.ref }}) by {{ build.author }}
    when:
      event: [ push, pull_request ]
      status: [ success, failure ]

branches: [develop, feature/*]

# services:
#   database:
#     image: mysql
#     # http://docs.drone.io/environment/
#     commands:
#       - export MYSQL_ROOT_PASSWORD="123"


