# http://docs.drone.io/cloning/
clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build:
    image: golang
    commands:
      - echo "hi"
      - go build

services:
  environment:
    - MYSQL_ROOT_PASSWORD="123"
  database:
    image: mysql



