# http://docs.drone.io/cloning/
clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build:
    image: golang
    commands:
      - echo "hi"
      - go build

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: tmp-slack-api-test

services:
  database:
    image: mysql
    # http://docs.drone.io/environment/
    commands:
      - export MYSQL_ROOT_PASSWORD="123"


