# http://docs.drone.io/cloning/
clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build:
    image: golang
    commands:
      - echo "hi"
      - go build

services:
  database:
    image: mysql
    commands:
      - export MYSQL_ROOT_PASSWORD="123"



