# http://docs.drone.io/cloning/
clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build:
    image: golang
    commands:
      - echo "hi"
      - go build

  notify:
    image: plugins/slack
    channel: tmp-slack-api-test

services:
  database:
    image: mysql
    # http://docs.drone.io/environment/
    commands:
      - export MYSQL_ROOT_PASSWORD="123"


