apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  labels:
    app: goapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: wzj8698/goapp:0.2
        ports:
        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: goapp
spec:
  selector:
    app: goapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: goapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: goapp.so.opensdev.pro
    http:
      paths:
      - path: /
        backend:
          serviceName: goapp
          servicePort: 80
