apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "wzj8698/goapp:0.2"
  artifacts:
  - imageName: wzj8698/goapp
    workspace: .
    docker: {}
  local: {}
deploy:
#  kubectl:
#    manifests:
#      - k8s-*
  helm:
    release:
    - name: goapp
      chartPath: goapp
      namespace: skaffold
      values:
        image: goapp
